### PR TITLE
Restructuring All Code with new feature

### PR DESCRIPTION
**Pull request by CCSleep**
**Notes**
Currently, this can only add and read student object using student ID, since I spent most of the time restructuring the code.

**Features**
- `utils/types` are now under `utils/schema` (this is to prevent conflict with `types` module in standard Python)
- All of database operations will be under `utils/crud.py`
- `utils/database.py` is repurposed for database connection, and all of the models will be in `utils/models.py`
- The API endpoint is now in the API router, located at `routes/v1.py`

### CODE REVIEW

**Review by galax028 — APPROVED** [review]

**Comment by sleepntsheep** [comment]
pog

**Comment by smartwhatt** [comment]
Hi, thank you for contributing but there're something that doesn't really fits our plan for these repo;
1. We're trying to move away from orm since they tends to create larger uneffient sql query.
2.  the router with v1 and long url isn't really work for this since we will have a graphql data interface which will take care of data and versionings and we would like to keep these services as simple and as maintainable as possible.
Other than this file structuring and tests are very cool.

Notes:
1. for commits messages we would do something like `feat: {what you did}` or `fix: {issue number} {how}`
    - https://www.conventionalcommits.org/en/v1.0.0/#summary
2. For branch name we use `(feature/fix/test/enhance/doc/style)/things-to-do`
3. If some feature might be similar or base off of some branch we would merge back to it

P.S. Sorry for not explaining this properly before you start working on this. We're currently making a community discord and I will update you on that.

**Comment by smartwhatt** [comment]
Discord: https://discord.gg/PNHE4QY5

**Comment by galax028** [comment]
Just a comment that I would like to add, I don't think it would be a necessity to use GraphQL since mysk is definitely not that big of an API, and I think GraphQL would just complicate things.

**Comment by smartwhatt** [comment]
mysk_full_architecture

This is the architecture we've planned for this and you can see that there will be multiple microservice working together and managing 10s url in the frontend would be a disaster.
 For why we use microservices, deploying a monolith website on a scale is not easy and updating and maintaining indivually would be more flexible to the maintainer and in term of techstack.

**Pull request merged**
